In [1]:
# IMPORTACION DE LIBRERIAS
import yaml
import os
import polars as pl
import pathlib

In [ ]:
# CONFIGURACION

# Rutas del proyecto
FILE_PATH = pathlib.Path(os.path.abspath("initial_prep.ipynb")) # os.path.abspath("initial_prep.ipynb")
MODULE_DIR = pathlib.Path(FILE_PATH).parent.parent
BASE_DIR = MODULE_DIR.parent

# Cargar el archivo de configuración
with open(pathlib.Path(FILE_PATH).parent.parent / "config.yml", "r") as f:
    config = yaml.safe_load(f)

# Rutas de los datos
RAW_DATA_DIR = pathlib.Path(BASE_DIR) / config["paths"]["raw_data"]
DW_DATA_DIR = pathlib.Path(BASE_DIR) / config["paths"]["dw_data"]

In [18]:
df = pl.read_parquet(DW_DATA_DIR / "rep_application_train.parquet")

In [20]:
df.head()

shape: (5, 123)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ ORGANIZAT │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ ION_TYPE_ │
│ i32        ┆ i32    ┆ ---        ┆ ---       ┆   ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  ┆ 2         │
│            ┆        ┆ str        ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ i32       ┆ i32       ┆ i32       ┆ str       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002     ┆ 1      ┆ Cash loans ┆ M         ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ Type 3    │
│ 100003     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ Type 0    │
│ 100004     ┆ 0      ┆ Revolving  ┆ M         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ Type 0    │
│            ┆        ┆ loans      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 100006     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ Type 3    │
│ 100007     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ Type 0    │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [21]:
df_raw = pl.read_csv(RAW_DATA_DIR / "application_train.csv")

In [22]:
df_raw

shape: (307_511, 122)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ i64        ┆ i64    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ str        ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002     ┆ 1      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 100003     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100004     ┆ 0      ┆ Revolving  ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│            ┆        ┆ loans      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 100006     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 100007     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 456251     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 456252     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 456253     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       │
│ 456254     ┆ 1      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 456255     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 2.0       ┆ 0.0       ┆ 1.0       │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘